### ISSUE TITLE
Archive Group Data doesn't work for Party

### ISSUE THREAD

**Issue by Ayrenne** [bumbleshoot/auto-archive-chats#2]
**What is the bug?**
"archiveGroupData" does not work for parties.

**How often does this happen?**
Every time I tried it.

**Script version**
Auto Archive Group Data v0.5.1

**How many chats was your script archiving when you encountered this bug/error?**
I was trying to archive challenges and other group data for one party.

<img width="806" alt="Screen Shot 2023-08-09 at 12 19 43 AM" src="https://github.com/bumbleshoot/auto-archive-group-data/assets/113395615/45f2c277-f769-43bb-886d-0cbf20188ab5">

------------

Update:
I tried archiving only the chat data for the party, and that didn't work either. Got the same error message again.

**Comment by bumbleshoot** [comment]
Thank you for reminding me to add party support to the script! It lost this feature during the mad rush to archive Habitica's guild data. Parties were not the focus at that time! Just a few lines of code were needed to bring this feature back - it is working now! 😊
